language: node_js

node_js:
- node

before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- aws configure set profile.mine.aws_access_key_id $AWS_ACCESS_KEY_ID
- aws configure set profile.mine.aws_secret_access_key $AWS_SECRET_ACCESS_KEY
- aws configure set profile.mine.region ap-southeast-1
- aws configure --profile mine list

install:
- npm i

script:
- make upload
