language: node_js
node_js:
- node
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- npm i
script:
- make upload
env:
  global:
  - secure: QMI2C810+rglg8lCDo8c0OI/hFHCmzhl4Z9jyvGKZv5amWH9bXeWdSNLMiWZn3Cz/X3uRVd7aw/dkmj8/EB6Lr6qeYpdHx+qApg0vzTgG6vZZ2+GlxHRbaPj0XqEzVUPjYbGfvkqUZR7LpDwBwUkL81hoqJlzob0jfdgcfT5Zi/KuA9ytFcgy72b2j3zr3EPFWgJm3GX4KQwjW2nm4rWsLcc9tQ+QeJe/yUPntMPJIcFosDqZFU+guNwmy3KWAyl1CBpiva1zTEgSDx/QzSbqNZdiA5Ss8lhITCtt5DdYnPS9iPXFfaryBFft9JIh1Na3kE0SEzcq/5WCT7lKeR6yXMKa3k/rcwjopLbwv17LVNv7+n3t30WEHBl/EA/bGjuz5VPbayKqVOkDzGu6T4iAjjq66lrRlweDl/x1Ed+F/aP4isbiJB8TxhHVa/idaiUZ7iSEi4H0VOxOcKqBGg8b9Fax/5tfeJbCx2mGTBLSTOryvw1gaqTQQLgwe4E8cvC1X0/QfxndEDc4MJluNg3I7y5Qka+P+QBcnbCkmYal9Zd6b5qhyBUHCEAF8tnTZuISNCm7aKQViJpoRhwhXIUXgaVhAVhMfKB2v0qTSO9REioixZoI9DgdCfZ9b2PsiySiTApXm01KDKlq9zqGsMcYBUJ2+Y1dsILbUdLjPVEZV0=
  - secure: BxoItiWx62T/DMWBFJW33s1qbynn1ba/Ifc3ywptbsMZhZpH8gUF4r7mmt4yBvEEf7ae9T+G4QYBghx75E95YZ/cmwwrschfeFilMO+Nnoqlrw0t3AVKBoTUsR140fRyrAVzrmBK7TaR07PPirzMC6ccTlh+poHh4Xh1GIJLayCKBJ5icKuQ35XJCiEjiELsJXVSh7G+zmyRf9naYrf1FW+a4KIBDOXl23zW/FVpfdugeiiV5CWuSPE9ikhCoLWS0ovDnkhvIRrez+3C9HW51/hpu8R4SS0MMAzQhEZdF7M4slzqVH+umuA2OJRSH6VDs/l6S2u7Tu6FwBIjyuWyx8W7wC8oKXl+9jL51blIHcUf3ATmqkQSxX4TwQDOw04QkcEdDa/Dbz/gnfPAUTr9GHyZm5ly4qjVErqkI7zvAINTorz48hZcoXJJY4VQVowr8fq/rXNpZ2sQjbBbDhXySTBqLt7IHmptdyfRsfOY8SQh7S3aOJ2rW31zw/EvpxjyWAa3Dj5fi1a0SMeQXEJ0S9sfU9lrhPm8BDJ3oZf/J/7/GNNZ5I03QYIyGRN/7qh3Ls4HF3Lg4EARVpa438YbioC3OJ9nG7GpJ1kZHl1NA94YG0lINV5vy8lngqh0sKatydNoGEI0L2UwpyzSr6rsBm4w8xBpcQrm7G7o0rFQhaQ=
