on:
  push:
    branches:
      - master

jobs:
  builddeploy:
    runs-on: ubuntu-latest
    name: Build homepage and deploy
    steps:
      - name: Checkout project files
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - run: make upload
